channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - numpy=1.23
  # - faiss-gpu=1.7.1
  - faiss
  - matplotlib
  - seaborn
  - hdf5storage
  - umap-learn
  - numba=0.55.1
  - scikit-image
  - cython
  - fftw
  - pandas
  - fbpca
  - ffmpeg
