# Folder path of data location
data_path: "./data/"

# Output folder of all plots
out_path: "./results/tutorial/"

# File path of skeletal specifications
skeleton_path: "../configs/skeletons/demo_mouse.yaml"

label: "fitsne"
downsample: 10

# Parameters for t-SNE embedding
single_embed:
  method: "fitsne"
  perplexity: 50
  lr: "auto"
  sigma: 15

# Parameters for embedding new data into an existing t-SNE embedding
transform_embed:
  method: "knn"
  k: 5
  sigma: 15
